project:
  type: book
  output-dir: docs

book:
  title: "PF 0953 Programación en R 2022-II"
  author: "Manuel Vargas"
  date: "2022-08-21"
  chapters:
    - index.qmd
    - part: part-01-introduccion.qmd
      chapters:
        - 01-introduccion-ciencia-datos-geoespaciales.qmd
        - 02-markdown.qmd
        - 03-git.qmd
    - part: part-02-lenguaje-programacion-r.qmd    
      chapters:
        - 04-pensamiento_computacional-arquitectura_computadoras.qmd    
    - part: part-06-evaluaciones.qmd
      chapters:
        - examen_corto-01.qmd        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

